### ISSUE TITLE
Design Christmas market and add it to the snow world.

### ISSUE THREAD

**Issue by leonleoff** [Gamify-IT/overworld#38]
## Requirement
A Christmas market has to be in the game

## Current Behavior
No Christmas market is in the Game

## Expected Behavior
A Christmas market is in the Game

## DoD
- [ ] Christmastree Design
- [ ] Gifts Design
- [ ] Schneeman Design
- [ ] Yeti Design
- [ ] Cansy Design
- [ ] Santa Design
- [ ] Christmas marketis in the Game

**Comment by delvh** [comment]
Please open issues in the issues repository, not here.
